module projectExplorer

open System.IO

let private isExcluded (excludedPaths: array<DirectoryInfo>) (file: FileInfo) =
    let rec loopUntilFoundOrEmpty (candidate: DirectoryInfo) =
        match candidate.Parent with
        | null -> false
        | parent ->
            let included = excludedPaths |> Seq.exists (fun p -> p.FullName = parent.FullName)
            if included then true else loopUntilFoundOrEmpty parent

    loopUntilFoundOrEmpty file.Directory

type AutogeneratedCSharpFile =
    | Auto of FileInfo
    | UserMade of FileInfo

type FoundFiles =
    { FSharpFiles: Map<string, FileInfo list>
      CSharpFiles: AutogeneratedCSharpFile list }

let headerMatchesAutoGenerated (f: FileInfo) =
    if f.Exists then
        use reader = f.OpenRead()
        let buffer = Array.zeroCreate csharpGenerator.headerWarning.Length
        let res = reader.Read(buffer, 0, csharpGenerator.headerWarning.Length)

        if res <> csharpGenerator.headerWarning.Length then
            false
        else
            csharpGenerator.headerWarning = System.Text.Encoding.UTF8.GetString buffer
    else
        true

let findFiles (path: string) =
    let excludedPaths =
        [| ".git"; ".godot" |]
        |> Array.map (fun s -> Path.Combine(path, s) |> DirectoryInfo)


    let files = Directory.EnumerateFiles(path, "*", SearchOption.AllDirectories)

    let isAllowedExtension (f: FileInfo) =
        f.Extension.EndsWith ".cs" || f.Extension.EndsWith ".fs"


    let fsharpFiles, csharpFiles =
        files
        |> Seq.map FileInfo
        |> Seq.filter isAllowedExtension
        |> Seq.filter (isExcluded excludedPaths >> not)
        |> Seq.sortBy (fun f -> f.FullName)
        |> Seq.toList
        |> List.partition (fun f -> f.Extension.EndsWith(".fs", System.StringComparison.OrdinalIgnoreCase))

    let map =
        fsharpFiles
        |> List.groupBy (fun f -> Path.GetFileNameWithoutExtension f.FullName)
        |> Map



    let processedCSharpFiles =
        csharpFiles
        |> List.map (fun f ->
            let matchesHead = headerMatchesAutoGenerated f
            if matchesHead then Auto f else UserMade f)

    { FSharpFiles = map
      CSharpFiles = processedCSharpFiles }
